# Puerto donde correrá tu API Gateway
server.port=8080

# Nombre de la aplicación
spring.application.name=filler-api-gateway

# ==========================================
# CONFIGURACIÓN DE CORS (Para el front)
# ==========================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# ==========================================
# RUTAS DE LOS MICROSERVICIOS
# ==========================================

# Ruta 1: Hacia filler-back-main
spring.cloud.gateway.routes[0].id=filler-back-main-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/main/**

# Ruta 2: Hacia filler-resumen (rama development)
spring.cloud.gateway.routes[1].id=filler-resumen-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/resumen/**